name: generate-prompt
on:
  workflow_dispatch:
    inputs:
      step:
        type: number
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (1) 파이썬 버전 명시
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # (2) 의존 설치
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (3) 프롬프트 빌더 실행
      - name: Build prompt
        run: |
          python scripts/build_prompt.py \
            --json workflow_template.json \
            --step "${{ inputs.step }}" \
            --var topic="테스트" \
            --out units/step_${{ inputs.step }}_draft.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
